export const integrationCategories = [
    { name: "Legal Essentials", id: "common", label: "Legal Essentials" },
    { name: "CRM & Sales", id: "crm", label: "CRM & Sales" },
    { name: "Communication", id: "communication", label: "Communication" },
    { name: "Document Storage", id: "documents", label: "Document Storage" },
    { name: "Productivity", id: "productivity", label: "Productivity" },
    { name: "Finance & Accounting", id: "finance", label: "Finance & Accounting" },
    { name: "APIs & Webhooks", id: "apis", label: "APIs & Webhooks" },
    { name: "AI & ML", id: "ai", label: "AI & ML" },
]

export const allIntegrations = [
    // Legal Essentials
    {
        name: "Clio",
        description:
            "Connect your practice management system to build automated workflows around case data and client records.",
        category: "common",
        categoryLabel: "Legal Practice",
        color: "bg-blue-50 text-blue-600",
        logo: "/Vector.svg",
    },
    {
        name: "Google Workspace",
        description:
            "Sync Google Drive, Gmail, and Calendar with your automated workflows for seamless document and email handling.",
        category: "common",
        categoryLabel: "Productivity",
        color: "bg-red-50 text-red-600",
        logo: "/google-drive.svg",
    },
    {
        name: "Slack",
        description: "Receive automated notifications, alerts, and case updates directly in your team Slack channels.",
        category: "common",
        categoryLabel: "Communication",
        color: "bg-emerald-50 text-emerald-600",
        logo: "/slack-integration.svg",
    },
    {
        name: "Microsoft 365",
        description: "Integrate Outlook, Teams, and OneDrive for seamless email and document automation.",
        category: "common",
        categoryLabel: "Productivity",
        color: "bg-sky-50 text-sky-600",
        logo: "/microsoft-outlook.svg",
    },
    {
        name: "Notion",
        description: "Automate data flow between your Notion databases and case management systems.",
        category: "common",
        categoryLabel: "Productivity",
        color: "bg-slate-50 text-slate-600",
        logo: "/notion.svg",
    },
    {
        name: "HTTP / REST APIs",
        description: "Build custom integrations with any software that exposes a REST API.",
        category: "common",
        categoryLabel: "Developer Tools",
        color: "bg-cyan-50 text-cyan-600",
    },

    // CRM & Sales
    {
        name: "Clio",
        description: "Advanced case management and client relationship tracking.",
        category: "crm",
        categoryLabel: "Legal Practice",
        color: "bg-blue-50 text-blue-600",
        logo: "/Vector.svg",
    },
    {
        name: "Salesforce",
        description: "Enterprise CRM integration for complex sales pipelines and client management.",
        category: "crm",
        categoryLabel: "CRM",
        color: "bg-sky-50 text-sky-600",
        logo: "/salesforce.svg",
    },
    {
        name: "HubSpot",
        description: "Free CRM platform ideal for smaller firms managing leads and client relationships.",
        category: "crm",
        categoryLabel: "CRM",
        color: "bg-orange-50 text-orange-600",
        logo: "/hubspot-integration.svg",
    },
    {
        name: "Airtable",
        description: "Flexible database for custom client tracking and matter management.",
        category: "crm",
        categoryLabel: "Databases",
        color: "bg-red-50 text-red-600",
        logo: "/airtable.svg",
    },
    {
        name: "Pipedrive",
        description: "Sales-focused CRM with powerful automation and reporting capabilities.",
        category: "crm",
        categoryLabel: "CRM",
        color: "bg-green-50 text-green-600",
        logo: "/pipedrive-integration.svg",
    },
    {
        name: "LawLion",
        description: "Modern legal-specific CRM designed for boutique law firms.",
        category: "crm",
        categoryLabel: "Legal Practice",
        color: "bg-purple-50 text-purple-600",
    },

    // Communication
    {
        name: "Slack",
        description: "Team messaging and notification hub for automated alerts.",
        category: "communication",
        categoryLabel: "Communication",
        color: "bg-emerald-50 text-emerald-600",
        logo: "/slack-integration.svg",
    },
    {
        name: "Microsoft Teams",
        description: "Enterprise team collaboration with integrated chat and notifications.",
        category: "communication",
        categoryLabel: "Communication",
        color: "bg-purple-50 text-purple-600",
        logo: "/teams-integration.svg",
    },
    {
        name: "Gmail / Google Mail",
        description: "Automated email workflows with filtering and labeling.",
        category: "communication",
        categoryLabel: "Email",
        color: "bg-red-50 text-red-600",
        logo: "/google-drive.svg",
    },
    {
        name: "Outlook / Exchange",
        description: "Enterprise email integration with advanced routing and automation.",
        category: "communication",
        categoryLabel: "Email",
        color: "bg-blue-50 text-blue-600",
        logo: "/microsoft-outlook.svg",
    },
    {
        name: "Twilio",
        description: "SMS and voice automation for client communications.",
        category: "communication",
        categoryLabel: "SMS/Voice",
        color: "bg-red-50 text-red-600",
        logo: "/twilio-integration.svg",
    },
    {
        name: "SendGrid",
        description: "Email delivery and automation platform for bulk communications.",
        category: "communication",
        categoryLabel: "Email",
        color: "bg-blue-50 text-blue-600",
    },

    // Document Storage
    {
        name: "Google Drive",
        description: "Cloud storage with integrated Google Workspace file management.",
        category: "documents",
        categoryLabel: "Cloud Storage",
        color: "bg-red-50 text-red-600",
        logo: "/google-drive.svg",
    },
    {
        name: "OneDrive / SharePoint",
        description: "Microsoft cloud storage with enterprise security and collaboration.",
        category: "documents",
        categoryLabel: "Cloud Storage",
        color: "bg-sky-50 text-sky-600",
        logo: "/sharepoint-integration.svg",
    },
    {
        name: "Dropbox",
        description: "Simple, reliable file storage and sharing for teams.",
        category: "documents",
        categoryLabel: "Cloud Storage",
        color: "bg-blue-50 text-blue-600",
        logo: "/dropbox-integration.svg",
    },
    {
        name: "Box",
        description: "Enterprise-grade document management with advanced security.",
        category: "documents",
        categoryLabel: "Cloud Storage",
        color: "bg-blue-50 text-blue-600",
    },
    {
        name: "AWS S3",
        description: "Scalable cloud storage for large-scale document management.",
        category: "documents",
        categoryLabel: "Cloud Storage",
        color: "bg-orange-50 text-orange-600",
    },
    {
        name: "iManage",
        description: "Legal-specific document management and matter management.",
        category: "documents",
        categoryLabel: "Legal Practice",
        color: "bg-slate-50 text-slate-600",
    },

    // Productivity
    {
        name: "Notion",
        description: "All-in-one workspace for databases, docs, and wikis.",
        category: "productivity",
        categoryLabel: "Workspace",
        color: "bg-slate-50 text-slate-600",
        logo: "/notion.svg",
    },
    {
        name: "Asana",
        description: "Project management and task tracking for teams.",
        category: "productivity",
        categoryLabel: "Project Management",
        color: "bg-blue-50 text-blue-600",
        logo: "/asana-integration.svg",
    },
    {
        name: "Monday.com",
        description: "Visual project management and workflow automation.",
        category: "productivity",
        categoryLabel: "Project Management",
        color: "bg-purple-50 text-purple-600",
        logo: "/monday-integration.svg",
    },
    {
        name: "Jira",
        description: "Issue tracking and agile project management.",
        category: "productivity",
        categoryLabel: "Project Management",
        color: "bg-blue-50 text-blue-600",
        logo: "/jira-integration.svg",
    },
    {
        name: "Trello",
        description: "Simple Kanban-style project management.",
        category: "productivity",
        categoryLabel: "Project Management",
        color: "bg-sky-50 text-sky-600",
        logo: "/trello-integration.svg",
    },
    {
        name: "Google Calendar",
        description: "Schedule management with automated reminders and syncing.",
        category: "productivity",
        categoryLabel: "Scheduling",
        color: "bg-red-50 text-red-600",
        logo: "/google-drive.svg",
    },

    // Finance & Accounting
    {
        name: "QuickBooks",
        description: "Accounting software integration for invoicing and financial tracking.",
        category: "finance",
        categoryLabel: "Accounting",
        color: "bg-green-50 text-green-600",
        logo: "/quickbooks-integration.svg",
    },
    {
        name: "FreshBooks",
        description: "Cloud accounting for small businesses with invoice automation.",
        category: "finance",
        categoryLabel: "Accounting",
        color: "bg-orange-50 text-orange-600",
    },
    {
        name: "Xero",
        description: "Online accounting software for small business finance management.",
        category: "finance",
        categoryLabel: "Accounting",
        color: "bg-blue-50 text-blue-600",
    },
    {
        name: "Stripe",
        description: "Payment processing and billing automation.",
        category: "finance",
        categoryLabel: "Payments",
        color: "bg-purple-50 text-purple-600",
        logo: "/stripe-integration.svg",
    },
    {
        name: "PayPal",
        description: "Payment processing and invoicing.",
        category: "finance",
        categoryLabel: "Payments",
        color: "bg-sky-50 text-sky-600",
    },
    {
        name: "Wave",
        description: "Free accounting software with invoice and expense tracking.",
        category: "finance",
        categoryLabel: "Accounting",
        color: "bg-indigo-50 text-indigo-600",
    },

    // APIs & Webhooks
    {
        name: "HTTP / REST APIs",
        description: "Direct API integration for any custom endpoint.",
        category: "apis",
        categoryLabel: "Developer Tools",
        color: "bg-cyan-50 text-cyan-600",
    },
    {
        name: "Zapier",
        description: "Pre-built integration platform with 5000+ apps.",
        category: "apis",
        categoryLabel: "Integration Platforms",
        color: "bg-orange-50 text-orange-600",
    },
    {
        name: "Make (formerly Integromat)",
        description: "Visual workflow automation with extensive integrations.",
        category: "apis",
        categoryLabel: "Integration Platforms",
        color: "bg-purple-50 text-purple-600",
    },
    {
        name: "n8n",
        description: "Open-source workflow automation and integration platform.",
        category: "apis",
        categoryLabel: "Integration Platforms",
        color: "bg-red-50 text-red-600",
        logo: "/n8n.svg",
    },
    {
        name: "Postman",
        description: "API development and testing platform.",
        category: "apis",
        categoryLabel: "Developer Tools",
        color: "bg-orange-50 text-orange-600",
    },
    {
        name: "GraphQL APIs",
        description: "Modern API standard for flexible data querying.",
        category: "apis",
        categoryLabel: "Developer Tools",
        color: "bg-pink-50 text-pink-600",
    },

    // AI & ML
    {
        name: "OpenAI / ChatGPT",
        description: "AI-powered text generation and analysis for case summaries.",
        category: "ai",
        categoryLabel: "AI",
        color: "bg-green-50 text-green-600",
        logo: "/openai.svg",
    },
    {
        name: "Google Gemini",
        description: "Advanced AI model for legal document analysis.",
        category: "ai",
        categoryLabel: "AI",
        color: "bg-blue-50 text-blue-600",
        logo: "/google-drive.svg",
    },
    {
        name: "Anthropic Claude",
        description: "Constitutional AI for nuanced legal analysis and research.",
        category: "ai",
        categoryLabel: "AI",
        color: "bg-slate-50 text-slate-600",
    },
    {
        name: "Hugging Face",
        description: "Open-source ML models for custom NLP applications.",
        category: "ai",
        categoryLabel: "ML",
        color: "bg-yellow-50 text-yellow-600",
    },
    {
        name: "Microsoft Copilot",
        description: "AI assistant integrated with Microsoft 365 applications.",
        category: "ai",
        categoryLabel: "AI",
        color: "bg-sky-50 text-sky-600",
        logo: "/microsoft-outlook.svg",
    },
    {
        name: "LexisNexis AI",
        description: "Legal-specific AI for research and case analysis.",
        category: "ai",
        categoryLabel: "Legal Practice",
        color: "bg-blue-50 text-blue-600",
    },
]
