export const integrationCategories = [
    { name: "Legal Essentials", id: "legal-essentials", label: "Legal Essentials" },
    { name: "CRM & Sales", id: "crm", label: "CRM & Sales" },
    { name: "Communication", id: "communication", label: "Communication" },
    { name: "Document Storage", id: "documents", label: "Document Storage" },
    { name: "Productivity", id: "productivity", label: "Productivity" },
    { name: "Finance & Marketing", id: "finance", label: "Finance & Marketing" },
    { name: "AI & ML", id: "ai", label: "AI & ML" },
    { name: "APIs & Webhooks", id: "apis", label: "APIs & Webhooks" },
]

export const allIntegrations = [
    // Legal Essentials
    {
        name: "Clio",
        description:
            "Connect your practice management system to build automated workflows around case data and client records.",
        category: "legal-essentials",
        categoryLabel: "Legal Practice",
        color: "bg-blue-50 text-blue-600",
        logo: "/Vector.svg",
    },
    {
        name: "Google Workspace",
        description:
            "Sync Google Drive, Gmail, and Calendar with your automated workflows for seamless document and email handling.",
        category: "legal-essentials",
        categoryLabel: "Productivity",
        color: "bg-red-50 text-red-600",
        logo: "/google-workspace-integration.svg",
    },
    {
        name: "Slack",
        description: "Receive automated notifications, alerts, and case updates directly in your team Slack channels.",
        category: "legal-essentials",
        categoryLabel: "Communication",
        color: "bg-emerald-50 text-emerald-600",
        logo: "/slack-integration.svg",
    },
    {
        name: "Microsoft 365",
        description: "Integrate Outlook, Teams, and OneDrive for seamless email and document automation.",
        category: "legal-essentials",
        categoryLabel: "Productivity",
        color: "bg-sky-50 text-sky-600",
        logo: "/microsoft-365-integration.svg",
    },
    {
        name: "Notion",
        description: "Automate data flow between your Notion databases and case management systems.",
        category: "legal-essentials",
        categoryLabel: "Productivity",
        color: "bg-slate-50 text-slate-600",
        logo: "/notion.svg",
    },
    {
        name: "HTTP / REST APIs",
        description: "Build custom integrations with any software that exposes a REST API.",
        category: "legal-essentials",
        categoryLabel: "Developer Tools",
        color: "bg-cyan-50 text-cyan-600",
    },

    // CRM & Sales
    {
        name: "Airtable",
        description: "Flexible database for custom client tracking and matter management.",
        category: "crm",
        categoryLabel: "Databases",
        color: "bg-red-50 text-red-600",
        logo: "/airtable.svg",
    },
    {
        name: "Salesforce",
        description: "Enterprise CRM integration for complex sales pipelines and client management.",
        category: "crm",
        categoryLabel: "CRM",
        color: "bg-sky-50 text-sky-600",
        logo: "/salesforce.svg",
    },
    {
        name: "HubSpot",
        description: "Free CRM platform ideal for smaller firms managing leads and client relationships.",
        category: "crm",
        categoryLabel: "CRM",
        color: "bg-orange-50 text-orange-600",
        logo: "/hubspot-integration.svg",
    },
    {
        name: "Pipedrive",
        description: "Sales-focused CRM with powerful automation and reporting capabilities.",
        category: "crm",
        categoryLabel: "CRM",
        color: "bg-green-50 text-green-600",
        logo: "/pipedrive-integration.svg",
    },
    {
        name: "Clio",
        description: "Advanced case management and client relationship tracking.",
        category: "crm",
        categoryLabel: "Legal Practice",
        color: "bg-blue-50 text-blue-600",
        logo: "/Vector.svg",
    },
    {
        name: "LawLion",
        description: "Modern legal-specific CRM designed for boutique law firms.",
        category: "crm",
        categoryLabel: "Legal Practice",
        color: "bg-purple-50 text-purple-600",
    },

    // Communication
    {
        name: "Slack",
        description: "Team messaging and notification hub for automated alerts.",
        category: "communication",
        categoryLabel: "Communication",
        color: "bg-emerald-50 text-emerald-600",
        logo: "/slack-integration.svg",
    },
    {
        name: "Microsoft Teams",
        description: "Enterprise team collaboration with integrated chat and notifications.",
        category: "communication",
        categoryLabel: "Communication",
        color: "bg-purple-50 text-purple-600",
        logo: "/teams-integration.svg",
    },
    {
        name: "Gmail",
        description: "Automated email workflows with filtering and labeling.",
        category: "communication",
        categoryLabel: "Email",
        color: "bg-red-50 text-red-600",
        logo: "/gmail-integration.svg",
    },
    {
        name: "Outlook / Exchange",
        description: "Enterprise email integration with advanced routing and automation.",
        category: "communication",
        categoryLabel: "Email",
        color: "bg-blue-50 text-blue-600",
        logo: "/microsoft-outlook.svg",
    },
    {
        name: "Twilio",
        description: "SMS and voice automation for client communications.",
        category: "communication",
        categoryLabel: "SMS/Voice",
        color: "bg-red-50 text-red-600",
        logo: "/twilio-integration.svg",
    },
    {
        name: "SendGrid",
        description: "Email delivery and automation platform for bulk communications.",
        category: "communication",
        categoryLabel: "Email",
        color: "bg-blue-50 text-blue-600",
    },

    // Storage
    {
        name: "Google Drive",
        description: "Cloud storage with integrated Google Workspace file management.",
        category: "documents",
        categoryLabel: "Cloud Storage",
        color: "bg-red-50 text-red-600",
        logo: "/google-drive.svg",
    },
    {
        name: "OneDrive / SharePoint",
        description: "Microsoft cloud storage with enterprise security and collaboration.",
        category: "documents",
        categoryLabel: "Cloud Storage",
        color: "bg-sky-50 text-sky-600",
        logo: "/sharepoint-integration.svg",
    },
    {
        name: "Dropbox",
        description: "Simple, reliable file storage and sharing for teams.",
        category: "documents",
        categoryLabel: "Cloud Storage",
        color: "bg-blue-50 text-blue-600",
        logo: "/dropbox-integration.svg",
    },
    {
        name: "Postgres",
        description: "Open source SQL database for building scalable backends.",
        category: "documents",
        categoryLabel: "Databases",
        color: "bg-blue-50 text-blue-600",
        logo: "/postgresql_integration.svg",
    },
    {
        name: "Supabase",
        description: "Open source Firebase alternative for building scalable backends with Postgres.",
        category: "documents",
        categoryLabel: "Databases",
        color: "bg-orange-50 text-orange-600",
        logo: "/supabase-integration.svg",
    },

    // Productivity
    {
        name: "Notion",
        description: "All-in-one workspace for databases, docs, and wikis.",
        category: "productivity",
        categoryLabel: "Workspace",
        color: "bg-slate-50 text-slate-600",
        logo: "/notion.svg",
    },
    {
        name: "Asana",
        description: "Project management and task tracking for teams.",
        category: "productivity",
        categoryLabel: "Project Management",
        color: "bg-blue-50 text-blue-600",
        logo: "/asana-integration.svg",
    },
    {
        name: "Monday.com",
        description: "Visual project management and workflow automation.",
        category: "productivity",
        categoryLabel: "Project Management",
        color: "bg-purple-50 text-purple-600",
        logo: "/monday-integration.svg",
    },
    {
        name: "Jira",
        description: "Issue tracking and agile project management.",
        category: "productivity",
        categoryLabel: "Project Management",
        color: "bg-blue-50 text-blue-600",
        logo: "/jira-integration.svg",
    },
    {
        name: "Trello",
        description: "Simple Kanban-style project management.",
        category: "productivity",
        categoryLabel: "Project Management",
        color: "bg-sky-50 text-sky-600",
        logo: "/trello-integration.svg",
    },
    {
        name: "Google Calendar",
        description: "Schedule management with automated reminders and syncing.",
        category: "productivity",
        categoryLabel: "Scheduling",
        color: "bg-red-50 text-red-600",
        logo: "/google-drive.svg",
    },

    // Finance & Marketing
    {
        name: "FreshBooks",
        description: "Cloud accounting for small businesses with invoice automation.",
        category: "finance",
        categoryLabel: "Accounting",
        color: "bg-orange-50 text-orange-600",
        logo: "/freshbooks-integration.svg",
    },
    {
        name: "Stripe",
        description: "Payment processing and billing automation.",
        category: "finance",
        categoryLabel: "Payments",
        color: "bg-purple-50 text-purple-600",
        logo: "/stripe-integration.svg",
    },
    {
        name: "WordPress",
        description: "Power your firm's website and blog with automated content publishing and lead capture.",
        category: "finance",
        categoryLabel: "Marketing",
        color: "bg-blue-50 text-blue-600",
        logo: "/wordpress-integration.svg",
    },
    {
        name: "Kit",
        description: "Automate your email marketing and creator commerce with powerful sequences and subscriber management.",
        category: "finance",
        categoryLabel: "Marketing",
        color: "bg-blue-50 text-blue-600",
        logo: "/kit-integration.svg",
    },
    {
        name: "Mailchimp",
        description: "Connect your marketing platform for automated lead nurturing and email campaigns.",
        category: "finance",
        categoryLabel: "Marketing",
        color: "bg-orange-50 text-orange-600",
        logo: "/mailchimp-integration.svg",
    },

    // AI & ML
    {
        name: "OpenAI / ChatGPT",
        description: "AI-powered text generation and analysis for case summaries.",
        category: "ai",
        categoryLabel: "AI",
        color: "bg-green-50 text-green-600",
        logo: "/openai.svg",
    },
    {
        name: "Google Gemini",
        description: "Advanced AI model for legal document analysis.",
        category: "ai",
        categoryLabel: "AI",
        color: "bg-blue-50 text-blue-600",
        logo: "/gemini-integration.svg",
    },
    {
        name: "Anthropic Claude",
        description: "Constitutional AI for nuanced legal analysis and research.",
        category: "ai",
        categoryLabel: "AI",
        // color: "bg-slate-50 text-slate-600",
        logo: "/claude-integration.svg",
    },
    {
        name: "Hugging Face",
        description: "Open-source ML models for custom NLP applications.",
        category: "ai",
        categoryLabel: "ML",
        color: "bg-yellow-50 text-yellow-600",
        logo: "/huggingface-integration.svg",
    },
    {
        name: "OpenRouter",
        description: "AI assistant integrated with Microsoft 365 applications.",
        category: "ai",
        categoryLabel: "AI",
        color: "bg-sky-50 text-sky-600",
        logo: "/openrouter-integration.svg",
    },

    // APIs & Webhooks
    {
        name: "HTTP / REST APIs",
        description: "Direct API integration for any custom endpoint.",
        category: "apis",
        categoryLabel: "Developer Tools",
        color: "bg-cyan-50 text-cyan-600",
        logo: "/http-integration.svg",
    },
    {
        name: "Webhooks",
        description: "Custom event notifications for automated workflows.",
        category: "apis",
        categoryLabel: "Developer Tools",
        color: "bg-cyan-50 text-cyan-600",
        logo: "/webhook-integration.svg",
    },
]
